spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8085

# register this auth-service at the eureka server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
      org.springframework.security: DEBUG
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator

  endpoint:
    health:
      show-details: always
