spring:
  application:
    name: COMPOSITE-SERVICE

## Eureka Client Configs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# Server Configs
server:
  port: 8080

## Resilience4j Configs
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
    instances:
      package:
        base-config: default
        wait-duration-in-open-state: 10s
      user:
        base-config: default
        wait-duration-in-open-state: 5s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 500
        enable-exponential-backoff: true

logging:
  level:
    root: info
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG
    feign: DEBUG
    org:
      springframework:
        cloud:
          openfeign: DEBUG

## Spring Actuator Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
