spring:
  application:
    name: OUTBOUND-SERVICE

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/OutboundServiceDB
      database: OutboundServiceDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    hostname: localhost

server:
  port: 8084
